export const FETCH_CURRENT_USER_START = 'users/FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_OK = 'users/FETCH_CURRENT_USER_OK';
export const FETCH_CURRENT_USER_ERROR = 'users/FETCH_CURRENT_USER_ERROR';


export const SET_CURRENT_USER = 'users/SET_CURRENT_USER';

